### ISSUE TITLE
New term DDSS

### ISSUE THREAD

**Issue by mverzocc** [DUNE/abcdune#14]
# Request for a new term

## Case 1: you know the definition
  The term to add to glossary, fully spelled out (e.g. `Anode Plane Assembly`):
```
DUNE Detector Safety System
```
  Official abbreviation, if any (e.g. `APA`):
```
DDSS
```

  Suggested identifier (short, lower case, no spaces, e.g. `apa`):
```
ddss
```

  Brief descriptive text or, if you know the DUNE LaTeX Glossary system you may provide a full glossary.tex entry:
```
The hardware system responsible for the safety of the detector, implemented either via a programmable logic controller (PLC) or via custom hardware protections. 
```

Any additional information about your term, (context of use, synonyms, links, citations, etc):
```
Used in the context of the detector safety system description. Sometimes referred to as "detector interlock".
```

## Case 2: you do not know the definition
Please describe below in which context you encountered the acronym.
See [DUNE's wiki page](https://wiki.dunescience.org/) to list the relevant working groups. Thank you.

**Comment by aheavey** [comment]
done
