### ISSUE TITLE
DSS

### ISSUE THREAD

**Issue by mverzocc** [DUNE/abcdune#15]
# Request for a new term

## Case 1: you know the definition
  The term to add to glossary, fully spelled out (e.g. `Anode Plane Assembly`):
```
Detector Support System
```
  Official abbreviation, if any (e.g. `APA`):
```
DSS
```

  Suggested identifier (short, lower case, no spaces, e.g. `apa`):
```
dss
```

  Brief descriptive text or, if you know the DUNE LaTeX Glossary system you may provide a full glossary.tex entry:
```
In the Single Phase Far Detector module this is the system of rails, suspended from the cryostat ceiling, that are used to support the arrays of the anode plane assemblies (APAs) and of cathode plane assemblies (CPAs), as well as the cathode end-walls.
```

Any additional information about your term, (context of use, synonyms, links, citations, etc):
```
Used in the description of the APA and CPA installation in the cryostat.
```

## Case 2: you do not know the definition
Please describe below in which context you encountered the acronym.
See [DUNE's wiki page](https://wiki.dunescience.org/) to list the relevant working groups. Thank you.

**Comment by aheavey** [comment]
done
