### ISSUE TITLE
PLC

### ISSUE THREAD

**Issue by mverzocc** [DUNE/abcdune#16]
# Request for a new term

## Case 1: you know the definition
  The term to add to glossary, fully spelled out (e.g. `Anode Plane Assembly`):
```
Programmable Logic Controller
```
  Official abbreviation, if any (e.g. `APA`):
```
PLC
```

  Suggested identifier (short, lower case, no spaces, e.g. `apa`):
```
plc
```

  Brief descriptive text or, if you know the DUNE LaTeX Glossary system you may provide a full glossary.tex entry:
```
A programmable logic controller (PLC) or programmable controller is an industrial digital computer which has been ruggerized and adapted for the control of manufacturing processes, such as assembly lines, or robotic devices, or any activity that requires high reliability, ease of programming and process fault diagnosis.
```

Any additional information about your term, (context of use, synonyms, links, citations, etc):
```
In DUNE PLCs are used in the controls of the cryogenic system and for the detector interlocks or DUNE detector safety system. They may also be used to control some detector hardware (for example this is the case with the heaters and the fans on the TPC electronics cryostat penetrations).
```

## Case 2: you do not know the definition
Please describe below in which context you encountered the acronym.
See [DUNE's wiki page](https://wiki.dunescience.org/) to list the relevant working groups. Thank you.

**Comment by aheavey** [comment]
done
