### ISSUE TITLE
New term: NP02

### ISSUE THREAD

**Issue by kherner** [DUNE/abcdune#17]
# Request for a new term

## Case 1: you know the definition
  The term to add to glossary, fully spelled out (e.g. `Anode Plane Assembly`):
```
NP02
```
  Official abbreviation, if any (e.g. `APA`):
```

```

  Suggested identifier (short, lower case, no spaces, e.g. `apa`):
```
np02
```

  Brief descriptive text or, if you know the DUNE LaTeX Glossary system you may provide a full glossary.tex entry:
```
\newduneword{np02}{NP02}{CERN designation for the ProtoDUNE Dual-Phase (\gls{dp}) detector.}
```

Any additional information about your term, (context of use, synonyms, links, citations, etc):
```

```

## Case 2: you do not know the definition
Please describe below in which context you encountered the acronym.
See [DUNE's wiki page](https://wiki.dunescience.org/) to list the relevant working groups. Thank you.

**Comment by aheavey** [comment]
done
