### ISSUE TITLE
Modify a term

### ISSUE THREAD

**Issue by aihimmel** [DUNE/abcdune#18]
# Request for a new term

## Case 1: you know the definition
  The term to add to glossary, fully spelled out (e.g. `Anode Plane Assembly`):
```
Photon Detection System
```
  Official abbreviation, if any (e.g. `APA`):
```
PDS
```

  Suggested identifier (short, lower case, no spaces, e.g. `apa`):
```

```

  Brief descriptive text or, if you know the DUNE LaTeX Glossary system you may provide a full glossary.tex entry:
```

```

Any additional information about your term, (context of use, synonyms, links, citations, etc):
```
Currently listed as "PD System", but that's a fairly unusual. Seeing it as PDS is much more common. The existing description is fine.
```

## Case 2: you do not know the definition
Please describe below in which context you encountered the acronym.
See [DUNE's wiki page](https://wiki.dunescience.org/) to list the relevant working groups. Thank you.

**Comment by aheavey** [comment]
I don't understand; it's set to render as PDS already.

**Comment by aihimmel** [comment]
I think Claire just fixed this this morning.
-Alex

On Sep 8, 2020, at 10:00 AM, aheavey <notifications@github.com<mailto:notifications@github.com>> wrote:



I don't understand; it's set to render as PDS already.

**Comment by aheavey** [comment]
Ok, thanks. Right -it’s in her part of the alphabet!
