### ISSUE TITLE
New term 

### ISSUE THREAD

**Issue by aihimmel** [DUNE/abcdune#19]
# Request for a new term

## Case 1: you know the definition
  The term to add to glossary, fully spelled out (e.g. `Anode Plane Assembly`):
```
ProtoDUNE (Single Phase/Dual Phase)
```
  Official abbreviation, if any (e.g. `APA`):
```
PD (PDSP/PDDP)
```

  Suggested identifier (short, lower case, no spaces, e.g. `apa`):
```

```

  Brief descriptive text or, if you know the DUNE LaTeX Glossary system you may provide a full glossary.tex entry:
```

```

Any additional information about your term, (context of use, synonyms, links, citations, etc):
```
Existing definitions are fine, but we should point out that the abbreviation "PD" is overloaded, and _sometimes_ refers to the photon detectors and _sometimes_ refers to protoDUNE.
```

## Case 2: you do not know the definition
Please describe below in which context you encountered the acronym.
See [DUNE's wiki page](https://wiki.dunescience.org/) to list the relevant working groups. Thank you.

**Comment by aheavey** [comment]
I prefer to leave PD as is; used only for photon detector. I would hope that it's used for ProtoDUNE only in very informal documents or communications where its meaning is clear. If it's used more widely, then we should add it - please open a new issue if this is the case.

**Comment by aihimmel** [comment]
I think (hope) you're right that PD by itself to mean "ProtoDUNE" is relatively uncommon and we shouldn't encourage it, but PDSP and PDDP _are_ quite common and I think should be included if they aren't already.

**Comment by aheavey** [comment]
Ah, ok. I have labels 'pdsp' and 'pddp' that render as ProtoDUNE-S(D)P, but hadn't realized that PDSP and PDDP were used; they aren't used in the formal design reports anyway. I'll reopen this issue, then Claire, I'd suggest copying the pdsp/pddp entries and just replacing the ProtoDUNE-S(D)P with PDS(D)P.

**Comment by aihimmel** [comment]
Right. I'm sure they never show up in formal documents, but they are certainly in common usage in emails/slack/meetings etc.
-Alex

On Oct 1, 2020, at 11:00 AM, aheavey <notifications@github.com<mailto:notifications@github.com>> wrote:



Ah, ok. I have labels 'pdsp' and 'pddp' that render as ProtoDUNE-S(D)P, but hadn't realized that PDSP and PDDP were used; they aren't used in the formal design reports anyway. I'll reopen this issue, then Claire, I'd suggest copying the pdsp/pddp entries and just replacing the ProtoDUNE-S(D)P with PDS(D)P.

**Comment by clairedavid** [comment]
Sorry this slipped under my radar and I haven't taken care of this old request.

@aihimmel  do you want me to replace ProtoDUNE-SP by PDSP and ProtoDUNE-DP (still a thing?) by PDDP?

**Comment by aihimmel** [comment]
I am pretty disconnected these days -- I am probably not the one to ask about this.
