### ISSUE TITLE
AC Coupling

### ISSUE THREAD

**Issue by tomjunk** [DUNE/abcdune#2]
**Paste below the acronym and its description**
AC
    capacitive coupling.

**Describe the issue**
AC usually means Alternating Current.  AC coupling on an oscilloscope always has a characteristic resistance and thus a characteristic RC time constant associated with it.

**Suggest a correction**
AC
  Alternating Current
when used in the phrase "AC coupling" refers to a circuit element that filters out low-frequency components, such as constant offsets, leaving higher frequency signal components.  The frequency filtering is determined both by a resistor and a capacitor.
```

```

**Additional context**
Add any other context, links or references about the correction here.

**Comment by aheavey** [comment]
Fixed
