### ISSUE TITLE
Correct term 

### ISSUE THREAD

**Issue by clairedavid** [DUNE/abcdune#4]
**Paste the term and its description below**
Paste the HTML or the LaTeX (preferred) for the term's entry here.
```
\newduneword{atlas}{ATLAS}{One of two general-purpose detectors at the \gls{lhc}. It investigates a wide range of physics, from the search for the Higgs boson to extra dimensions and particles that could make up \gls{dm}}
```

**Describe the issue**
Give a clear and concise explanation of what is inaccurate in the current entry.
```
The Higgs was found.
```

**Suggest a correction**
Write the (in LaTeX, if possible) your suggested correction here.
```
\newduneword{atlas}{ATLAS}{One of two general-purpose detectors at the \gls{lhc}. It investigates a wide range of physics, from the measurements of the Higgs boson properties to searches for extra dimensions and particles that could make up \gls{dm}}
```

**Additional context**
Add any other context, links, or references about the correction here.
```

```

**Comment by aheavey** [comment]
I updated the ATLAS entry accordingly. I did it within github so it's not tested. I probably shouldn't do it that way.
